# Generated by Django 3.1.4 on 2020-12-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer_text',
            name='self_name',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
