# Generated by Django 3.1.4 on 2020-12-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_footer_text_self_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer_text',
            name='self_name',
        ),
        migrations.AddField(
            model_name='footer_text',
            name='name',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
