# Generated by Django 3.1.4 on 2020-12-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20201221_0653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer_contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mail', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('adress', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='footer_text',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
