# Generated by Django 3.1.4 on 2020-12-27 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='city',
            new_name='final_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='prices_sum',
        ),
    ]
